version: "3.9"

services:

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ocr-qa:
    build: .
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
    stdin_open: true
    tty: true

volumes:
  qdrant_storage:
